# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: sample.tsv
coldata: coldata.tsv
condition: condition.tsv

run:
    # Can be a list if pair-end : "R1,R2" or "1,2"
    type: "1,2"
    # For sortmeRNA if pair-end
    way: "fwd,rev"
    # paired or unpaired fastq file
    reads: "paired"
    # Extension for the input fastq file
    ext: "fastq"

ref:
    # Reference Genome (must be unziped)
    genome: "2606217280.fna"
    # The Hisat index
    index: "04_index/2606217280"
    # gtf file with transcripts
    annotation: "2606217280.gtf"
    # Gene id for the figures
    geneid: "gene_id"
    # Gene identifier for the gtf
    geneidentifier: "transcript"
    # Database for SortMeRNA
    ddb: "01_Reference/silva-bac-16s-id90.fasta"

trimmomatic:
    # File with the adaptaters to remove
    adaptaters: "/media/thomas/data/mio_filella_crocosphaera/01_Reference/NexteraPE-PE.fa"
    leading: 20
    trailing: 15
    minlen: 36

qiime:
    # Type of data
    type: "SampleData[PairedEndSequencesWithQuality]"
    # Format for importing data with qiime2: manifest file (PairedEndFastqManifestPhred33V2 or PairedEndFastqManifestPhred64V2, etc.) or folder (CasavaOneEightSingleLanePerSampleDirFmt)
    # See https://docs.qiime2.org/2021.2/tutorials/importing/ for more information
    format: "PairedEndFastqManifestPhred33V2"
    # Project name
    name: "crocosphaera"   

# Dada2
dada2:
    truncation_err: 2
    truncation_len-f: 0
    truncation_len-r: 0
    trim-left-f: 0
    trim-left-r: 0
    quality_err-f: 2
    quality_err-r: 2
    seqlenth: 90 # IMPORTANT parameter corresponding to the minimum length of merged reads to keep
    training: 1000000 # should be set higher for a non-test dataset: default: 1000000
    chimera: pooled
    threads: 12 # if 0 all available cores will be used

# Taxonomy
taxonomy:
    database_classified: "silva-138-99-nb-classifier.qza"
    confidence: 0.7
    njobs: 4 # Be carefull with the memory usage
    filter: "d__Eukaryota"

# Diversity
diversity:
    mindepth: 10
    # Take the mean of merged sequence after denoising and filtering (used for the axis limit of the alpha rarefaction plot)
    maxdepth: 64500
    # See the alpha rarefaction visualization (when the alpha diversity stabilized) and the feature table summary (to see the nb of sample below the rarefaction depth)
    samplingdepth: 333

## Functional annotation with microbeannotator
microbeannotator:
    # Folder in which all databases will be downloaded and stored
    folder: "01_Reference/MicrobeAnnotator_DB"
    # [blast,diamond,sword] the search method you intend to use.
    method: "diamond"
    # Number of processors used to format the databases
    threads: 12
    # Regular (Kofam database, the Swissprot, Trembl and RefSeq databases) or light (Kofam and Swissprot) mode for the database to annotate proteins
    lightversion: "regular"
    # Input fasta files (separated by spaces)
    protfiles: "01_Reference/2606217280.genes.faa"
    # Number of protein files to be processed simultaneously
    processes: 1
    # Folder to store all results generated by MicrobeAnnotator
    annotationfolder: "01_Reference/MicrobeAnnotator"

filtering:
    # Run to remove from the bulk RNA-seq analyse after fastqc introspection (separated by ,) in the cpm_filtering.R script. Can be ""
    #rmrun: "P2598_Ca-1_PVHD16,P2598_Ca-2_PVHD17,P2598_Ca-3_PVHD18,P2598_ScNI-1_PVHD1,P2598_ScNI-2_PVHD2,P2598_ScNI-3_PVHD3,P2598_Sc_At-1_PVHD10,P2598_Sc_At-2_PVHD11,P2598_Sc_At-3_PVHD12,P2598_Sc_Sp-1_PVHD7,P2598_Sc_Sp-2_PVHD8,P2598_Sc_Sp-3_PVHD9"
    rmrun: ""
    #rmproj: "Ca-1,Ca-2,Ca-3,ScNI-1,ScNI-2,ScNI-3,Sc_At-1,Sc_At-2,Sc_At-3,Sc_Sp-1,Sc_Sp-2,Sc_Sp-3"
    rmproj: ""
    # cpm threshold to filter the low expressed genes
    thresh_cpm: 1
    # Minimum number of samples to have a high expressed genes (depending of the cpm threshold)
    thresh_sample: 3

pca:
    labels:
        # columns of sample sheet to use for PCA
        - condition

diffexp:
    # Reference to do the comparison
    ref_level: "Sc_Sc"
    # Shrinkage estimator for ranking and visualization (apeglm, normal or ashr)
    lfcshrink_type: "apeglm"
    # Gene name to see the expression between the condition (can be a list of genes)
    gene_name: "YOR122C,YLL050C,YOR181W,YDL029W,YJR065C,YKL007W,YIL034C,YNL079C,YIL138C,YNL271C,YIL159W,YDR129C,YMR092C,YGR080W,YNL138W,YLR429W,YIL062C,YLR370C,YKL013C,YNR035C,YBR234C,YCR088W,YHR023W,YKL129C,YMR109W,YIR006C,YDR063W,YLR319C,YPL242C,YOR239W,YOR326W,YAL029C,YFL039C,Sc[Ca],N2,Ca"
    # Mutant to represent the gene with the top p-value
    mutant_level: "N19_Ca"
    # Number of genes to select with the best p-value
    nbpval: 50
    # qvalue threshold
    pCutoff: 0.01
    # Foldchange threshold (not in log base 2)
    FCcutoff: 2
